task:
  only_if: $CIRRUS_BRANCH == 'main' || $CIRRUS_BRANCH == 'develop' || $CIRRUS_TAG != '' || $CIRRUS_PR != ''
  env:
    CIRRUS_CLONE_SUBMODULES: true

  matrix:
    - name: Test build

      # Default is 2 CPUs and 4 GB of memory
      arm_container:
        cpu: 4
        memory: 6G
        matrix:
          - image: python:3.7
          - image: python:3.11

      install_build_dependencies_script: |
        apt-get update
        apt-get -qq -y install --no-install-recommends \
          gcc \
          g++ \
          libboost-dev \
          libmpfr-dev \
          libgmp-dev \
          swig \
          autoconf \
          libtool \
          patch \
          automake

      create_venv_script: |
        python -m venv ../venv

      install_script: |
        . ../venv/bin/activate
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --verbose .
        python -m pip list

      pytest_script: |
        . ../venv/bin/activate
        python -m pip install --upgrade pytest
        python -m pip list
        pytest -vv -rs -Wd
